# Dataset Introduction



In [ ]:
# Import Libraries
import numpy as np
import pandas as pd

print("Libraries imported successfully!")

Libraries imported successfully!


d:\Work\ADSML\Capstone Project\ADSML_GIT\CAPSTONE\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [5]:
# Test Code
tr = np.ones((3, 3))
print(tr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


# Import Dataset



In [8]:
# Import Kaggle Dataset
df = pd.read_csv('./dataset/AAPL.csv')
print(df.head())

         Date      Open      High       Low     Close  Adj Close     Volume
0  1980-12-12  0.128348  0.128906  0.128348  0.128348   0.100178  469033600
1  1980-12-15  0.122210  0.122210  0.121652  0.121652   0.094952  175884800
2  1980-12-16  0.113281  0.113281  0.112723  0.112723   0.087983  105728000
3  1980-12-17  0.115513  0.116071  0.115513  0.115513   0.090160   86441600
4  1980-12-18  0.118862  0.119420  0.118862  0.118862   0.092774   73449600
